on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

name: Push or PR 

jobs:
  sbt:
    name: Setup, build and test
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'
    - name: Install deps
      run: npm install
    - name: Building packages
      run: npm run build
    - name: Unit testing
      run: npm run test:unit
    - name: ESLint
      run: npm run test:lint
    - name: Type checking
      run: npm run test:types
